name: Build and deploy Marp slides

on:
  push:
    branches:
      - main  # ή άλλαξέ το στο branch που χρησιμοποιείς για το README.md σου

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Marp CLI
      run: npm install -g @marp-team/marp-cli

    - name: Build slides to HTML
      run: marp README.md --html --output index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
